services:
  guitar-bot:
    build: .
    container_name: guitar-bot
    restart: always
    env_file: .env
    volumes:
      - ./archive:/app/archive
      - ./user_settings.json:/app/user_settings.json
      - ./topics_history.json:/app/topics_history.json
